### PR TITLE
Adding default editor config

### PR DESCRIPTION
**Pull request by spekulatius**

### CODE REVIEW

**Comment by anselmdk** [comment]
I think this will have to wait until we've done the psr-2 conversion, as the editorconfig suggests  spaces instead of tabs (which is what's currently in the code base)

**Comment by spekulatius** [comment]
I have run the conversion to PSR-2 and opened this PR: https://github.com/titledk/silverstripe-calendar/pull/26

Please have a look and let me know if you have any concerns @anselmdk

**Comment by anselmdk** [comment]
Perfect!

**Comment by spekulatius** [comment]
:)

**Pull request merged**
